(function(){'use strict';
const $=id=>document.getElementById(id),core=EditorCore;let working={},saved={},layerId=core.definitions[0].id,selected=-1,page=0,dirty=false,formDirty=false,editorMap=null,preview=null,handles=null,activeGeometry=null;const size=25;let drawing=null,drawLayer=null,contextLayer=null;
const def=()=>core.definitions.find(d=>d.id===layerId),data=()=>working[layerId],text=(e,v)=>e.textContent=String(v??'');
function report(message,bad=false){text($('editorStatus'),message);$('editorStatus').className=bad?'editor-error':'editor-success';}
function run(fn){try{fn();}catch(e){report(e.message,true);}}
function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function backup(){return {format:'zondoma-webmap-edits-v1',savedAt:new Date().toISOString(),layers:working};}
function abandonForm(){if(drawing){if(!confirm('Abandonner le dessin en cours ?'))return false;stopDrawing();}return !formDirty||confirm('Les modifications non appliquées de cette entité seront abandonnées. Continuer ?');}
function markDirty(){dirty=true;report('Brouillon modifié. Enregistrez pour actualiser la carte.');}
function fields(){return core.fields(data());}
function refreshSchema(){const select=$('editorField');select.replaceChildren();fields().forEach(name=>{const o=document.createElement('option');o.value=name;text(o,name);select.append(o);});}
function matching(){const q=MapUtils.normalize($('editorSearch').value);return data().features.map((f,i)=>({f,i})).filter(({f})=>!q||Object.values(f.properties).some(v=>MapUtils.normalize(v).includes(q)));}
function renderTable(){const rows=matching(),max=Math.max(0,Math.ceil(rows.length/size)-1);page=Math.min(page,max);const table=$('editorTable');table.replaceChildren();const keys=fields(),head=document.createElement('tr');['#',...keys].forEach(k=>{const th=document.createElement('th');text(th,k);head.append(th);});const thead=document.createElement('thead');thead.append(head);table.append(thead);const body=document.createElement('tbody');rows.slice(page*size,(page+1)*size).forEach(({f,i})=>{const tr=document.createElement('tr');tr.tabIndex=0;tr.className=i===selected?'selected':'';[i+1,...keys.map(k=>f.properties[k])].forEach(v=>{const td=document.createElement('td');text(td,v);tr.append(td);});tr.onclick=()=>{if(!abandonForm())return;selectFeature(i);};tr.onkeydown=e=>{if(e.key==='Enter')tr.click();};body.append(tr);});table.append(body);text($('editorPage'),rows.length+' entité(s) · page '+(page+1)+' / '+(max+1));$('editorPrevious').disabled=page===0;$('editorNext').disabled=page>=max;}
function refreshLayer(){stopDrawing();if(preview&&editorMap){editorMap.removeLayer(preview);preview=null;}if(handles)handles.clearLayers();selected=-1;formDirty=false;page=0;$('editorFeatureForm').hidden=true;text($('editorFeatureTitle'),'Sélectionnez une entité');refreshSchema();renderTable();if(editorMap)renderContext();}
function attributeRow(name,value){const row=document.createElement('div');row.className='editor-attribute';row.dataset.field=name;const label=document.createElement('label');text(label,name);const input=document.createElement('input');input.value=value==null?'':String(value);input.setAttribute('aria-label',name);const type=document.createElement('select');type.setAttribute('aria-label','Type du champ '+name);[['string','Texte'],['number','Nombre'],['boolean','Booléen'],['null','Vide']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;text(o,t);type.append(o);});type.value=value==null?'null':typeof value;input.disabled=type.value==='null';type.onchange=()=>{input.disabled=type.value==='null';formDirty=true;};input.oninput=()=>formDirty=true;row.append(label,input,type);return row;}
function selectFeature(index){selected=index;formDirty=false;const f=data().features[index];text($('editorFeatureTitle'),'Entité '+(index+1)+' — '+(f.properties.Nom||def().name));$('editorFeatureForm').hidden=false;$('editorAttributes').replaceChildren();fields().forEach(k=>$('editorAttributes').append(attributeRow(k,f.properties[k])));activeGeometry=core.clone(f.geometry);$('editorGeometry').value=JSON.stringify(activeGeometry,null,2);renderTable();requestAnimationFrame(()=>renderGeometry(true));}
function ensureMap(){if(editorMap)return;editorMap=L.map('geometryEditorMap',{maxZoom:22}).setView(map.getCenter(),map.getZoom());editorMap.attributionControl.setPrefix('Édition des géométries');L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png',{subdomains:'abc',maxNativeZoom:20,maxZoom:22,attribution:'© OpenStreetMap · OSM France'}).addTo(editorMap);handles=L.layerGroup().addTo(editorMap);drawLayer=L.layerGroup().addTo(editorMap);editorMap.on('click',event=>{if(!drawing)return;drawing.points.push([event.latlng.lng,event.latlng.lat]);updateDrawing();if(def().family==='point')run(finishDrawing);});renderContext();}
function renderContext(){if(contextLayer)editorMap.removeLayer(contextLayer);contextLayer=L.geoJSON(data(),{onEachFeature:(f,layer)=>{layer.on('click',event=>{if(drawing)return;if(!abandonForm())return;const index=data().features.indexOf(f);if(index>=0)selectFeature(index);if(event.originalEvent)L.DomEvent.stopPropagation(event.originalEvent);});},style:{color:'#547d84',weight:1,fillOpacity:.07},pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:5,color:'#547d84',interactive:true})}).addTo(editorMap);if(preview)preview.bringToFront();}
function stopDrawing(){drawing=null;if(drawLayer)drawLayer.clearLayers();$('digitizeTools').hidden=true;if(editorMap){editorMap.doubleClickZoom.enable();editorMap.getContainer().classList.remove('digitizing');}text($('digitizeStatus'),'Cliquez sur un objet, puis déplacez ses points rouges. Terminez avec Enregistrer.');}
function updateDrawing(){drawLayer.clearLayers();const points=drawing.points,ll=points.map(p=>[p[1],p[0]]);ll.forEach(p=>L.circleMarker(p,{radius:5,color:'#ce3043',fillOpacity:1}).addTo(drawLayer));if(ll.length>1)(def().family==='polygon'&&ll.length>2?L.polygon(ll,{color:'#ce3043',fillOpacity:.12}):L.polyline(ll,{color:'#ce3043'})).addTo(drawLayer);text($('digitizeStatus'),def().name+' · '+points.length+' sommet(s). '+(def().family==='point'?'Cliquez pour placer le point.':'Cliquez pour ajouter les sommets, puis Terminer le dessin.'));}
function beginDrawing(replace){if(replace&&selected<0)throw Error('Sélectionnez une entité à redessiner.');if(drawing)stopDrawing();if(!replace&&!abandonForm())return;ensureMap();editorMap.invalidateSize();drawing={replace,index:selected,points:[]};if(preview){editorMap.removeLayer(preview);preview=null;}handles.clearLayers();$('digitizeTools').hidden=false;editorMap.doubleClickZoom.disable();editorMap.getContainer().classList.add('digitizing');updateDrawing();}
function finishDrawing(){if(!drawing)return;const geometry=core.drawnGeometry(drawing.points,def().family),replace=drawing.replace,index=drawing.index;stopDrawing();if(replace){selected=index;activeGeometry=geometry;$('editorGeometry').value=JSON.stringify(geometry,null,2);renderGeometry(false);data().features[selected].geometry=core.clone(geometry);delete data().features[selected].bbox;delete data().bbox;markDirty();renderContext();report('Objet redessiné. Cliquez sur Enregistrer.');}else{const properties=Object.fromEntries(fields().map(k=>[k,null]));data().features.push({type:'Feature',properties,geometry});delete data().bbox;markDirty();selectFeature(data().features.length-1);renderContext();report('Objet ajouté. Vous pouvez renseigner son nom et ses informations, puis cliquer sur Enregistrer.');}}
$('startDigitize').onclick=()=>run(()=>beginDrawing(false));$('replaceDigitize').onclick=()=>run(()=>beginDrawing(true));$('finishDigitize').onclick=()=>run(finishDrawing);$('undoDigitize').onclick=()=>{if(drawing){drawing.points.pop();updateDrawing();}};$('cancelDigitize').onclick=()=>{stopDrawing();if(selected>=0)renderGeometry(false);};
function renderGeometry(fit){ensureMap();editorMap.invalidateSize();if(preview)editorMap.removeLayer(preview);handles.clearLayers();preview=L.geoJSON({type:'Feature',properties:{},geometry:activeGeometry},{style:{color:'#ce3043',weight:3,fillOpacity:.12},pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:8,color:'#ce3043'})}).addTo(editorMap);if(fit&&preview.getBounds().isValid())editorMap.fitBounds(preview.getBounds(),{padding:[25,25],maxZoom:16});let handleCount=0;const polygon=activeGeometry.type.includes('Polygon');function handle(refs){if(handleCount++>=1500)return;const point=refs[0],marker=L.marker([point[1],point[0]],{draggable:true,icon:L.divIcon({className:'editor-vertex',iconSize:[12,12],iconAnchor:[6,6]})}).addTo(handles);marker.on('dragend',()=>{const ll=marker.getLatLng();refs.forEach(p=>{p[0]=ll.lng;p[1]=ll.lat;});$('editorGeometry').value=JSON.stringify(activeGeometry,null,2);data().features[selected].geometry=core.clone(activeGeometry);delete data().features[selected].bbox;delete data().bbox;markDirty();renderGeometry(false);renderContext();report('Position modifiée. Cliquez sur Enregistrer.');});}function walk(a){if(typeof a[0]==='number'){handle([a]);return;}if(Array.isArray(a[0])&&typeof a[0][0]==='number'){const closed=polygon&&JSON.stringify(a[0])===JSON.stringify(a[a.length-1]);a.forEach((p,i)=>{if(closed&&i===a.length-1)return;handle(closed&&i===0?[p,a[a.length-1]]:[p]);});}else a.forEach(walk);}walk(activeGeometry.coordinates);if(handleCount>1500)report('Les 1500 premiers sommets sont déplaçables ; utilisez le GeoJSON pour les autres.');}
function applyFeature(){if(selected<0)return;const properties={};[...$('editorAttributes').children].forEach(row=>properties[row.dataset.field]=core.value(row.querySelector('input').value,row.querySelector('select').value));const geometry=core.geometry(JSON.parse($('editorGeometry').value),def().family),f=data().features[selected];f.properties=properties;f.geometry=geometry;delete f.bbox;delete data().bbox;activeGeometry=core.clone(geometry);formDirty=false;markDirty();renderTable();}
core.definitions.forEach(d=>{const o=document.createElement('option');o.value=d.id;text(o,d.name);$('editorLayer').append(o);});
$('openDataEditor').onclick=()=>{if(!Object.keys(working).length){core.definitions.forEach(d=>{saved[d.id]=core.clone(window[d.variable]);working[d.id]=core.clone(saved[d.id]);});refreshLayer();}if(window.webmapEditorLoadError)report(window.webmapEditorLoadError,true);$('dataEditorDialog').showModal();requestAnimationFrame(()=>{ensureMap();editorMap.invalidateSize();});};
$('closeDataEditor').onclick=()=>{if(abandonForm()){if(formDirty&&selected>=0)selectFeature(selected);$('dataEditorDialog').close();}};$('dataEditorDialog').addEventListener('cancel',e=>{if(!abandonForm())e.preventDefault();else if(formDirty&&selected>=0)selectFeature(selected);});
$('editorLayer').onchange=()=>{if(!abandonForm()){$('editorLayer').value=layerId;return;}layerId=$('editorLayer').value;$('editorSearch').value='';refreshLayer();};$('editorSearch').oninput=()=>{page=0;renderTable();};$('editorPrevious').onclick=()=>{page--;renderTable();};$('editorNext').onclick=()=>{page++;renderTable();};$('editorGeometry').oninput=()=>formDirty=true;
$('previewEditorGeometry').onclick=()=>run(()=>{activeGeometry=core.clone(core.geometry(JSON.parse($('editorGeometry').value),def().family));renderGeometry(true);});$('applyEditorFeature').onclick=()=>run(applyFeature);
$('addEditorField').onclick=()=>run(()=>{if(!abandonForm())return;core.addField(data(),$('editorFieldName').value,core.value($('editorFieldDefault').value,$('editorFieldType').value));markDirty();refreshLayer();});
$('renameEditorField').onclick=()=>run(()=>{if(!abandonForm())return;const old=$('editorField').value;if(!old)throw Error('Sélectionnez un champ.');core.renameField(data(),old,$('editorFieldName').value);markDirty();refreshLayer();});
$('deleteEditorField').onclick=()=>run(()=>{const name=$('editorField').value;if(!name)throw Error('Sélectionnez un champ.');if(!abandonForm()||!confirm('Supprimer le champ « '+name+' » et toutes ses valeurs du brouillon ?'))return;data().features.forEach(f=>delete f.properties[name]);markDirty();refreshLayer();});
$('deleteEditorFeature').onclick=()=>run(()=>{if(selected<0||!confirm('Supprimer cette entité du brouillon ?'))return;data().features.splice(selected,1);delete data().bbox;markDirty();refreshLayer();});
$('newEditorFeature').onclick=()=>run(()=>beginDrawing(false));
$('undoEditorLayer').onclick=()=>{if(!confirm('Annuler tous les changements non enregistrés de cette couche ?'))return;working[layerId]=core.clone(saved[layerId]);markDirty();refreshLayer();};
$('saveEditor').onclick=()=>run(()=>{if(drawing)throw Error('Terminez ou annulez le dessin avant d’enregistrer.');if(formDirty)applyFeature();core.definitions.forEach(d=>core.validate(working[d.id],d.family));try{localStorage.setItem(window.webmapStorageKey,JSON.stringify(backup()));}catch(e){throw Error('Enregistrement dans le navigateur impossible. Exportez une sauvegarde JSON ou les fichiers .js pour conserver les changements.');}dirty=false;formDirty=false;location.reload();});
$('exportEditorBackup').onclick=()=>run(()=>{if(drawing)throw Error('Terminez ou annulez le dessin avant d’exporter.');if(formDirty)applyFeature();core.definitions.forEach(d=>core.validate(working[d.id],d.family));download('ZONDOMA_sauvegarde_donnees.json',JSON.stringify(backup(),null,2));});
$('exportEditorGeojson').onclick=()=>run(()=>{if(drawing)throw Error('Terminez ou annulez le dessin avant d’exporter.');if(formDirty)applyFeature();core.validate(data(),def().family);download(layerId+'.geojson',JSON.stringify(data(),null,2));});
$('exportEditorJs').onclick=()=>run(()=>{if(drawing)throw Error('Terminez ou annulez le dessin avant d’exporter.');if(formDirty)applyFeature();core.validate(data(),def().family);download(def().file,'var '+def().variable+' = '+JSON.stringify(data())+';\n','text/javascript');});
async function importFile(input,all){const file=input.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(all){if(parsed.format!=='zondoma-webmap-edits-v1'||!parsed.layers)throw Error('Format de sauvegarde inconnu.');const candidate={};core.definitions.forEach(d=>candidate[d.id]=core.clone(core.validate(parsed.layers[d.id],d.family)));if(!confirm('Remplacer les six couches du brouillon par cette sauvegarde ?'))return;working=candidate;}else{const candidate=core.clone(core.validate(parsed,def().family));if(!confirm('Remplacer toute la couche « '+def().name+' » du brouillon par ce GeoJSON ?'))return;working[layerId]=candidate;}markDirty();refreshLayer();}catch(e){report(e.message,true);}finally{input.value='';}}
$('importEditorGeojson').onchange=()=>importFile($('importEditorGeojson'),false);$('importEditorBackup').onchange=()=>importFile($('importEditorBackup'),true);
window.addEventListener('beforeunload',event=>{if(dirty||formDirty||drawing){event.preventDefault();event.returnValue='';}});
})();
