(function(root){'use strict';
const definitions=[['Limitedelaprovince_1','Limite de la province','polygon'],['limitedecommune_2','Communes','polygon'],['Plandeau_3','Plans d’eau','polygon'],['Coursdeau_4','Cours d’eau','line'],['Route_5','Routes','line'],['Localit_6','Localités','point']].map(([id,name,family])=>({id,name,family,variable:'json_'+id,file:id+'.js'}));
const clone=v=>JSON.parse(JSON.stringify(v));
function fieldName(name){if(typeof name!=='string'||!name.trim()||['__proto__','prototype','constructor'].includes(name))throw Error('Nom de champ vide ou réservé.');return name.trim();}
function fields(data){return [...new Set(data.features.flatMap(f=>Object.keys(f.properties)))];}
function position(p){if(!Array.isArray(p)||p.length<2||p.length>3||p.some(v=>typeof v!=='number'||!Number.isFinite(v))||Math.abs(p[0])>180||Math.abs(p[1])>90)throw Error('Coordonnée invalide : utilisez longitude, latitude en WGS84.');}
function line(a,min){if(!Array.isArray(a)||a.length<min)throw Error('Nombre insuffisant de sommets.');a.forEach(position);}
function polygon(a){if(!Array.isArray(a)||!a.length)throw Error('Polygone vide.');a.forEach(r=>{line(r,4);if(JSON.stringify(r[0])!==JSON.stringify(r[r.length-1]))throw Error('Chaque anneau doit être fermé : premier et dernier sommets identiques.');});}
function geometry(g,family){if(!g||typeof g!=='object')throw Error('Géométrie requise.');const families={Point:'point',MultiPoint:'point',LineString:'line',MultiLineString:'line',Polygon:'polygon',MultiPolygon:'polygon'};if(!families[g.type]||family&&families[g.type]!==family)throw Error('Type de géométrie incompatible avec cette couche.');const c=g.coordinates;if(g.type==='Point')position(c);else if(g.type==='MultiPoint')line(c,1);else if(g.type==='LineString')line(c,2);else if(g.type==='Polygon')polygon(c);else {if(!Array.isArray(c)||!c.length)throw Error('Géométrie vide.');c.forEach(x=>g.type==='MultiLineString'?line(x,2):polygon(x));}return g;}
function validate(data,family){if(!data||data.type!=='FeatureCollection'||!Array.isArray(data.features))throw Error('Le fichier doit être une FeatureCollection GeoJSON.');if(data.crs&&!JSON.stringify(data.crs).includes('4326')&&!JSON.stringify(data.crs).includes('CRS84'))throw Error('Importez en WGS84 (EPSG:4326).');data.features.forEach((f,i)=>{try{if(f.type!=='Feature'||!f.properties||Array.isArray(f.properties)||typeof f.properties!=='object')throw Error('Attributs invalides.');Object.keys(f.properties).forEach(fieldName);Object.values(f.properties).forEach(v=>{if(v!==null&&!['string','number','boolean'].includes(typeof v)||typeof v==='number'&&!Number.isFinite(v))throw Error('Les attributs doivent être texte, nombre, booléen ou null.');});geometry(f.geometry,family);}catch(e){throw Error('Entité '+(i+1)+' : '+e.message);}});return data;}
function value(raw,type){if(type==='null')return null;if(type==='number'){if(String(raw).trim()===''||!Number.isFinite(Number(raw)))throw Error('Valeur numérique invalide.');return Number(raw);}if(type==='boolean'){if(raw===true||raw==='true')return true;if(raw===false||raw==='false')return false;throw Error('Booléen : true ou false.');}return String(raw);}
function addField(data,name,defaultValue){name=fieldName(name);if(fields(data).includes(name))throw Error('Ce champ existe déjà.');data.features.forEach(f=>f.properties[name]=defaultValue);}
function renameField(data,oldName,newName){newName=fieldName(newName);if(newName!==oldName&&fields(data).includes(newName))throw Error('Ce nom existe déjà.');data.features.forEach(f=>{if(Object.hasOwn(f.properties,oldName)){const v=f.properties[oldName];delete f.properties[oldName];f.properties[newName]=v;}});}
function drawnGeometry(points,family){const p=clone(points);p.forEach(position);const unique=new Set(p.map(x=>JSON.stringify(x))).size;const min=family==='point'?1:family==='line'?2:3;if(unique<min)throw Error('Ajoutez au moins '+min+' sommet(s) distinct(s).');const g=family==='point'?{type:'Point',coordinates:p[0]}:family==='line'?{type:'LineString',coordinates:p}:{type:'Polygon',coordinates:[[...p,clone(p[0])]]};return geometry(g,family);}
const api={definitions,clone,fields,fieldName,geometry,validate,value,addField,renameField,drawnGeometry};root.EditorCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
