(function(){
'use strict';
const $=id=>document.getElementById(id);
const layers=[{name:'OSM France',layer:layer_OSMStandard_0,icon:'▧'}, {name:'Limite de la province',layer:layer_Limitedelaprovince_1,data:json_Limitedelaprovince_1,icon:'⬡'}, {name:'Communes',layer:layer_limitedecommune_2,data:json_limitedecommune_2,icon:'⬡'}, {name:'Plans d’eau',layer:layer_Plandeau_3,data:json_Plandeau_3,icon:'◒'}, {name:'Cours d’eau',layer:layer_Coursdeau_4,data:json_Coursdeau_4,icon:'〰'}, {name:'Routes',layer:layer_Route_5,data:json_Route_5,icon:'╱'}, {name:'Localités',layer:cluster_Localit_6,geo:layer_Localit_6,data:json_Localit_6,icon:'●'}];
const text=(el,value)=>el.textContent=String(value??'');
layers.forEach((item,i)=>{const card=document.createElement('label');card.className='layer-card';const check=document.createElement('input');check.type='checkbox';check.checked=map.hasLayer(item.layer);check.setAttribute('aria-label',item.name);const icon=document.createElement('span');icon.className='layer-icon';text(icon,item.icon);const info=document.createElement('div'),title=document.createElement('strong'),count=document.createElement('small'),status=document.createElement('span');text(title,item.name);text(count,item.data?item.data.features.length+' entité'+(item.data.features.length>1?'s':''):'Fond de carte');info.append(title,count);status.className='visibility';const sync=()=>{check.checked=map.hasLayer(item.layer);text(status,check.checked?'Visible':'Masqué');};sync();check.onchange=()=>{const requested=check.checked;if(item.layer===cluster_Localit_6&&equipmentActive)clearResults();if(requested)map.addLayer(item.layer);else map.removeLayer(item.layer);sync();};map.on('layeradd layerremove',event=>{if(event.layer===item.layer)sync();});card.append(check,icon,info,status);$('layerCards').append(card);if(item.data){const option=document.createElement('option');option.value=i;text(option,item.name);$('queryLayer').append(option);}});
$('queryLayer').value='6';
function addCriterion(){const item=layers[$('queryLayer').value],row=document.createElement('div');row.className='criterion';const field=document.createElement('select');field.setAttribute('aria-label','Champ');const keys=[...new Set(item.data.features.flatMap(f=>Object.keys(f.properties)))];keys.forEach(k=>{const o=document.createElement('option');o.value=k;text(o,k);field.append(o);});if(keys.includes('Nom'))field.value='Nom';const remove=document.createElement('button');text(remove,'×');remove.setAttribute('aria-label','Supprimer ce critère');remove.onclick=()=>{if($('criteria').children.length>1)row.remove();};const vals=document.createElement('div');vals.className='value-row';const op=document.createElement('select');op.setAttribute('aria-label','Opérateur');[['contains','Contient'],['eq','Égal à'],['neq','Différent de'],['gt','Supérieur à'],['gte','Supérieur ou égal'],['lt','Inférieur à'],['lte','Inférieur ou égal'],['empty','Vide'],['notempty','Non vide']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;text(o,t);op.append(o);});const value=document.createElement('input');value.placeholder='Choisir ou saisir';value.setAttribute('aria-label','Valeur recherchée');op.onchange=()=>{value.disabled=['empty','notempty'].includes(op.value);};const list=document.createElement('datalist');list.id='values-'+Math.random().toString(36).slice(2);value.setAttribute('list',list.id);function refresh(){list.replaceChildren();[...new Set(item.data.features.map(f=>f.properties[field.value]).filter(v=>v!=null))].sort((a,b)=>String(a).localeCompare(String(b),'fr')).forEach(v=>{const o=document.createElement('option');o.value=v;list.append(o);});value.value='';}field.onchange=refresh;refresh();vals.append(op,value);row.append(field,remove,vals,list);$('criteria').append(row);}
$('queryLayer').onchange=()=>{$('criteria').replaceChildren();addCriterion();};$('addCriterion').onclick=addCriterion;addCriterion();
map.createPane('searchHighlights');map.getPane('searchHighlights').style.zIndex=650;
let highlights=L.geoJSON(null,{onEachFeature:(f,layer)=>{if(f.properties.Statut!==undefined)layer.bindPopup(localityPopup(f),{className:'locality-popup',maxWidth:340,minWidth:240});else{const div=document.createElement('div');text(div,f.properties.Nom||'Entité');layer.bindPopup(div);}},pane:'searchHighlights',style:{color:'#cf3043',weight:4,fillOpacity:.2},pointToLayer:(f,ll)=>L.circleMarker(ll,{pane:'searchHighlights',radius:10,color:'#cf3043',fillColor:'#fff',fillOpacity:1,weight:4})});
function focus(feature){if(feature.geometry.type==='Point'){const ll=L.latLng(feature.geometry.coordinates[1],feature.geometry.coordinates[0]);map.setView(ll,Math.max(map.getZoom(),13));}else map.fitBounds(L.geoJSON(feature).getBounds(),{padding:[35,35],maxZoom:15});}
let currentMatches=[],currentKeys=[],currentLayer='',equipmentActive=false,restoreLocalities=false;
function restoreEquipmentLayer(){if(equipmentActive&&restoreLocalities)map.addLayer(cluster_Localit_6);equipmentActive=false;restoreLocalities=false;}
function zoomOverview(){const bounds=bounds_group.getBounds();if(bounds.isValid())map.fitBounds(bounds,{padding:[20,20]});else text($('mapStatus'),'Aucune géométrie disponible. Ajoutez ou importez des entités depuis Mise à jour.');}
function resizeMap(){requestAnimationFrame(()=>map.invalidateSize());}
function clearResults(){restoreEquipmentLayer();currentMatches=[];currentKeys=[];$('exportCsv').disabled=true;$('results').hidden=true;$('resultsTable').replaceChildren();map.removeLayer(highlights);resizeMap();}
$('closeResults').onclick=clearResults;
$('queryLayer').onchange=()=>{clearResults();$('criteria').replaceChildren();addCriterion();};
$('searchButton').onclick=()=>{
const item=layers[$('queryLayer').value];
const rules=[...$('criteria').children].map(row=>({field:row.querySelector('select').value,op:row.querySelector('.value-row select').value,value:row.querySelector('input').value.trim()})).filter(r=>r.value!==''||['empty','notempty'].includes(r.op));
if(rules.some(r=>['gt','lt','gte','lte'].includes(r.op)&&!Number.isFinite(Number(r.value)))){text($('mapStatus'),'Saisissez une valeur numérique pour les comparaisons.');return;}
restoreEquipmentLayer();const matches=MapUtils.filter(item.data.features,rules,$('queryLogic').value);showResults(matches,item,item.name);
};
function showResults(matches,item,title){
currentMatches=matches;currentLayer=title;currentKeys=[...new Set(item.data.features.flatMap(f=>Object.keys(f.properties)))];
highlights.clearLayers();highlights.addData(matches);highlights.addTo(map);$('results').hidden=false;$('exportCsv').disabled=matches.length===0;text($('resultsTitle'),matches.length+' résultat(s) — '+title);
const table=$('resultsTable');table.replaceChildren();const thead=document.createElement('thead'),head=document.createElement('tr');currentKeys.forEach(k=>{const th=document.createElement('th');th.scope='col';text(th,k);head.append(th);});thead.append(head);table.append(thead);const body=document.createElement('tbody');matches.forEach(f=>{const tr=document.createElement('tr');tr.tabIndex=0;tr.setAttribute('aria-label','Localiser '+(f.properties.Nom||'cette entité'));tr.onclick=()=>{body.querySelectorAll('tr').forEach(r=>r.classList.remove('selected'));tr.classList.add('selected');focus(f);};tr.onkeydown=e=>{if(e.key==='Enter')tr.click();};currentKeys.forEach(k=>{const td=document.createElement('td');text(td,f.properties[k]);tr.append(td);});body.append(tr);});if(!matches.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=currentKeys.length;text(td,'Aucun résultat. Modifiez les critères.');tr.append(td);body.append(tr);}table.append(body);text($('mapStatus'),matches.length+' entité(s) trouvée(s).');requestAnimationFrame(()=>{map.invalidateSize();if(matches.length)map.fitBounds(highlights.getBounds(),{padding:[25,25],maxZoom:13});});
};
$('exportCsv').onclick=()=>{if(!currentMatches.length)return;const blob=new Blob([MapUtils.csv(currentMatches,currentKeys)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='resultats_'+currentLayer.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_')+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('resetButton').onclick=()=>{clearResults();$('queryLogic').value='and';$('criteria').replaceChildren();addCriterion();text($('mapStatus'),'');zoomOverview();};$('extentButton').onclick=()=>zoomOverview();$('locateButton').onclick=()=>{text($('mapStatus'),'Recherche de votre position…');map.locate({setView:true,maxZoom:14});};map.on('locationfound',e=>{L.circleMarker(e.latlng,{color:'#176d48',radius:8}).addTo(map).bindPopup('Votre position').openPopup();text($('mapStatus'),'Position localisée.');});map.on('locationerror',()=>text($('mapStatus'),'Position indisponible. Autorisez la localisation dans votre navigateur.'));
let osmErrors=0;layer_OSMStandard_0.on('tileerror',()=>{osmErrors++;text($('mapStatus'),'OSM France : certaines tuiles sont indisponibles. Vérifiez votre connexion ; les couches restent consultables.');});layer_OSMStandard_0.on('tileload',()=>{if(!osmErrors)text($('mapStatus'),'Fond OSM France chargé.');});layer_OSMStandard_0.on('loading',()=>{osmErrors=0;});
const features=json_Localit_6.features;[['Localités',features.length],['Communes',json_limitedecommune_2.features.length],['Plans d’eau',json_Plandeau_3.features.length]].forEach(([name,n])=>{const d=document.createElement('div');d.className='stat';const b=document.createElement('b'),span=document.createElement('span');text(b,n);text(span,name);d.append(b,span);$('stats').append(d);});
const equipment={EQposte:'Poste',EQecole:'École',EQgendarme:'Gendarmerie',EQpolice:'Police',EQdouane:'Douane',EQcontrole:'Contrôle',EQhopital:'Hôpital',EQsanitair:'Centre sanitaire',EQAnimiste:'Lieu animiste',EQChretien:'Lieu chrétien',EQMusulman:'Lieu musulman',Marche:'Marché'};
function localityPopup(feature){const properties=feature.properties,box=document.createElement('article');box.className='locality-info';const header=document.createElement('header');header.className='locality-info-header';const kicker=document.createElement('span');kicker.className='locality-kicker';text(kicker,'LOCALITÉ · ZONDOMA');const title=document.createElement('h3');text(title,properties.Nom||'Localité sans nom');header.append(kicker,title);box.append(header);const body=document.createElement('div');body.className='locality-info-body';const meta=document.createElement('p');meta.className='locality-meta';const status=properties.Statut==='VILLAGE_ADMIN'?'Village administratif':String(properties.Statut||'Statut non renseigné').replace(/_/g,' ');text(meta,(properties.Nom_1?'Commune de '+properties.Nom_1+' · ':'')+status);body.append(meta);const available=Object.entries(equipment).filter(([key])=>Number(properties[key])>0);const heading=document.createElement('h4');text(heading,'Équipements disponibles ('+available.length+')');body.append(heading);if(available.length){const list=document.createElement('ul');list.className='locality-equipment-list';available.forEach(([,name])=>{const li=document.createElement('li');text(li,name);list.append(li);});body.append(list);}else{const none=document.createElement('p');none.className='locality-empty';text(none,'Aucun équipement recensé dans les données.');body.append(none);}box.append(body);return box;}
layer_Localit_6.eachLayer(layer=>layer.bindPopup(localityPopup(layer.feature),{className:'locality-popup',maxWidth:340,minWidth:240}));
const equipmentColors=['#176d48','#3277b5','#d08a24','#a74767','#735aab','#167e88','#ba4d3e','#55843d','#866848','#4b67ac','#916598','#427e74'];
const equipmentKeys=Object.keys(equipment);
const communeNames=[...new Set(features.map(f=>f.properties.Nom_1).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));
['pieCommune','infrastructureCommune'].forEach(id=>communeNames.forEach(name=>{const o=document.createElement('option');o.value=name;text(o,name);$(id).append(o);}));
function showDashboardContext(commune,key){if(!equipmentActive){restoreLocalities=map.hasLayer(cluster_Localit_6);equipmentActive=true;}map.removeLayer(cluster_Localit_6);const keys=key?[key]:equipmentKeys,matches=MapUtils.equipmentFilter(features,keys,commune,'or'),columns=['Nom','Statut','Nom_1',...keys],item={data:{features:features.map(f=>({properties:Object.fromEntries(columns.map(k=>[k,f.properties[k]]))}))}};showResults(matches,item,(commune||'Toute la province')+' — '+(key?equipment[key]:'tous les équipements'));$('dashboardDialog').close();resizeMap();}
function renderPie(){const g=MapUtils.aggregateEquipment(features,equipmentKeys,$('pieCommune').value),ns='http://www.w3.org/2000/svg';$('pieChart').replaceChildren();text($('pieSummary'),g.name+' · '+g.equipmentTotal+' présences · '+g.total+' localités');const card=document.createElement('section');card.className='pie-card';
const layout=document.createElement('div');layout.className='pie-layout';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 240 240');svg.setAttribute('role','group');svg.setAttribute('aria-label',g.name+' : répartition de '+g.equipmentTotal+' présences par type');let angle=-Math.PI/2;
g.counts.filter(c=>c.count>0).forEach(c=>{const delta=c.count/g.equipmentTotal*Math.PI*2,end=angle+delta;let shape;if(c.count===g.equipmentTotal){shape=document.createElementNS(ns,'circle');shape.setAttribute('cx',120);shape.setAttribute('cy',120);shape.setAttribute('r',106);}else{shape=document.createElementNS(ns,'path');shape.setAttribute('d',`M120 120 L${120+106*Math.cos(angle)} ${120+106*Math.sin(angle)} A106 106 0 ${delta>Math.PI?1:0} 1 ${120+106*Math.cos(end)} ${120+106*Math.sin(end)} Z`);}shape.setAttribute('fill',equipmentColors[Object.keys(equipment).indexOf(c.key)]);shape.setAttribute('stroke','#fff');shape.setAttribute('stroke-width','2');shape.setAttribute('tabindex','0');shape.setAttribute('role','button');const label=equipment[c.key]+' : '+c.count+' ('+c.percentage.toLocaleString('fr',{maximumFractionDigits:1})+' %)';shape.setAttribute('aria-label',g.name+' — '+label);const title=document.createElementNS(ns,'title');title.textContent=label;shape.append(title);shape.onclick=()=>showDashboardContext(g.scope,c.key);shape.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();shape.onclick();}};svg.append(shape);if(c.percentage>=7){const t=document.createElementNS(ns,'text'),mid=angle+delta/2;t.setAttribute('x',120+68*Math.cos(mid));t.setAttribute('y',120+68*Math.sin(mid));t.setAttribute('text-anchor','middle');t.setAttribute('fill','#fff');t.setAttribute('font-size','13');t.setAttribute('font-weight','bold');t.setAttribute('pointer-events','none');t.textContent=c.count+' · '+c.percentage.toLocaleString('fr',{maximumFractionDigits:0})+' %';svg.append(t);}angle=end;});
if(!g.equipmentTotal){const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',120);circle.setAttribute('cy',120);circle.setAttribute('r',106);circle.setAttribute('fill','#e7eeea');svg.append(circle);const t=document.createElementNS(ns,'text');t.setAttribute('x',120);t.setAttribute('y',120);t.setAttribute('text-anchor','middle');t.textContent='Aucun équipement';svg.append(t);}
const legend=document.createElement('div');legend.className='pie-legend';g.counts.forEach(c=>{const button=document.createElement('button');button.className='pie-legend-row';const dot=document.createElement('span'),label=document.createElement('span'),count=document.createElement('b');dot.className='legend-dot';dot.style.background=equipmentColors[Object.keys(equipment).indexOf(c.key)];text(label,equipment[c.key]);text(count,c.count+' · '+c.percentage.toLocaleString('fr',{maximumFractionDigits:1})+' %');button.append(dot,label,count);button.onclick=()=>showDashboardContext(g.scope,c.key);legend.append(button);});layout.append(svg,legend);card.append(layout);$('pieChart').append(card);}
Object.entries(equipment).forEach(([key,name])=>{const o=document.createElement('option');o.value=key;text(o,name);$('infrastructureType').append(o);});$('infrastructureType').value='EQecole';
function renderInfrastructure(){const commune=$('infrastructureCommune').value,key=$('infrastructureType').value,data=MapUtils.infrastructureDistribution(features,key,commune);text($('infrastructureSummary'),data.count+' localité'+(data.count>1?'s':'')+' sur '+data.total+' · '+data.percentage.toLocaleString('fr',{maximumFractionDigits:1})+' %');$('infrastructureList').replaceChildren();$('infrastructureEmpty').hidden=data.count!==0;$('showInfrastructureTable').disabled=data.count===0;data.matches.forEach(f=>{const li=document.createElement('li'),button=document.createElement('button');button.className='infrastructure-locality';text(button,f.properties.Nom||'Localité sans nom');button.title='Localiser '+(f.properties.Nom||'cette localité')+' · '+(f.properties.Nom_1||'');button.onclick=()=>{showDashboardContext(commune,key);requestAnimationFrame(()=>{focus(f);const marker=highlights.getLayers().find(l=>l.feature===f);if(marker)marker.openPopup();});};li.append(button);$('infrastructureList').append(li);});}
$('pieCommune').onchange=renderPie;$('infrastructureCommune').onchange=renderInfrastructure;$('infrastructureType').onchange=renderInfrastructure;
$('clearPieCommune').onclick=()=>{$('pieCommune').value='';renderPie();};$('clearInfrastructureCommune').onclick=()=>{$('infrastructureCommune').value='';renderInfrastructure();};
$('showPieTable').onclick=()=>showDashboardContext($('pieCommune').value);$('showInfrastructureTable').onclick=()=>showDashboardContext($('infrastructureCommune').value,$('infrastructureType').value);
$('clearDashboardTable').onclick=()=>{clearResults();text($('mapStatus'),'');zoomOverview();};
renderPie();renderInfrastructure();$('dashboardButton').onclick=()=>$('dashboardDialog').showModal();$('closeDashboard').onclick=()=>$('dashboardDialog').close();
window.addEventListener('resize',resizeMap);if(typeof ResizeObserver!=='undefined')new ResizeObserver(resizeMap).observe($('map'));map.invalidateSize();zoomOverview();
})();
