(function(root){
'use strict';
const normalize=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function match(properties,rule){const value=properties[rule.field],target=rule.value;if(rule.op==='empty')return value==null||value==='';if(rule.op==='notempty')return value!=null&&value!=='';if(['gt','lt','gte','lte'].includes(rule.op)){if(value==null||value===''||!Number.isFinite(Number(value))||!Number.isFinite(Number(target)))return false;const a=Number(value),b=Number(target);return rule.op==='gt'?a>b:rule.op==='lt'?a<b:rule.op==='gte'?a>=b:a<=b;}const a=normalize(value),b=normalize(target);return rule.op==='eq'?a===b:rule.op==='neq'?a!==b:a.includes(b);}
function filter(features,rules,logic){if(!rules.length)return features.slice();return features.filter(f=>logic==='or'?rules.some(r=>match(f.properties,r)):rules.every(r=>match(f.properties,r)));}
function csv(features,keys){const cell=value=>{let s=String(value??'');if(/^[\s]*[=+@-]/.test(s)&&!/^\s*-?\d+(?:[.,]\d+)?\s*$/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return '\uFEFF'+[keys.map(cell).join(';'),...features.map(f=>keys.map(k=>cell(f.properties[k])).join(';'))].join('\r\n');}
function equipmentRows(features,keys,commune,search,equipment){return features.filter(f=>communeMatches(f.properties.Nom_1,commune)&&normalize(f.properties.Nom).includes(normalize(search))).map(f=>({feature:f,value:equipment==='all'?keys.filter(k=>Number(f.properties[k])>0).length:(Number(f.properties[equipment])>0?1:0)})).sort((a,b)=>b.value-a.value||String(a.feature.properties.Nom).localeCompare(String(b.feature.properties.Nom),'fr'));}
function communeMatches(name,commune){return Array.isArray(commune)?commune.includes(name):!commune||name===commune;}
function equipmentFilter(features,keys,commune,logic){if(!keys.length)return [];return features.filter(f=>communeMatches(f.properties.Nom_1,commune)&&(logic==='and'?keys.every(k=>Number(f.properties[k])>0):keys.some(k=>Number(f.properties[k])>0)));}
function communeEquipment(features,keys,commune,logic){const matches=equipmentFilter(features,keys,commune,logic);const names=[...new Set(features.map(f=>f.properties.Nom_1||'Non renseignée'))].filter(n=>communeMatches(n,commune)).sort((a,b)=>a.localeCompare(b,'fr'));return names.map(name=>({name,total:features.filter(f=>(f.properties.Nom_1||'Non renseignée')===name).length,counts:keys.map(key=>({key,features:matches.filter(f=>(f.properties.Nom_1||'Non renseignée')===name&&Number(f.properties[key])>0)}))}));}
function equipmentTotals(groups){return groups.map(g=>{const total=g.counts.reduce((sum,c)=>sum+c.features.length,0);return {...g,equipmentTotal:total,counts:g.counts.map(c=>({...c,count:c.features.length,percentage:total?c.features.length/total*100:0}))};});}
function aggregateEquipment(features,keys,commune){const scoped=features.filter(f=>!commune||f.properties.Nom_1===commune);const counts=keys.map(key=>({key,features:scoped.filter(f=>Number(f.properties[key])>0)}));return equipmentTotals([{name:commune||'Toute la province',scope:commune||'',total:scoped.length,counts}])[0];}
function infrastructureDistribution(features,key,commune){const scoped=features.filter(f=>!commune||f.properties.Nom_1===commune);const matches=scoped.filter(f=>Number(f.properties[key])>0).slice().sort((a,b)=>String(a.properties.Nom||'').localeCompare(String(b.properties.Nom||''),'fr'));return {total:scoped.length,count:matches.length,percentage:scoped.length?matches.length/scoped.length*100:0,matches};}
root.MapUtils={normalize,match,filter,csv,equipmentRows,equipmentFilter,communeEquipment,equipmentTotals,aggregateEquipment,infrastructureDistribution};if(typeof module!=='undefined')module.exports=root.MapUtils;
})(typeof window!=='undefined'?window:globalThis);
